version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - VAR1="test purpose variable"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: taskdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123