"""empty message

Revision ID: 929242c857ea
Revises: 08eab26a187c
Create Date: 2024-03-22 20:40:02.231195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929242c857ea'
down_revision = '08eab26a187c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
